/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github

import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.test.runTest
import kotlin.test.Test
import kotlin.test.assertNotNull

private val logger: KLogger = KotlinLogging.logger {}

private class AppTest private constructor() {
    @Test
    fun appHasAGreeting() = runTest {
        logger.info { "thread: ${Thread.currentThread()}" }
        assertNotNull("", "app should have a greeting")
    }
    @Test
    fun `test zip and unzip`() = runTest {
        logger.info { "thread: ${Thread.currentThread()}" }
    }
}
