/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test-jvm:1.10.2")


    // This dependency is used by the application.
    implementation(libs.guava)

    // brotli解压
    implementation("org.brotli:dec:0.1.2")
    // 归档文件压缩、解压缩
    implementation("org.apache.commons:commons-compress:1.28.0")
    // kotlin 日志门面
    implementation("io.github.oshai:kotlin-logging:8.0.01")
    // 日志实现
    implementation("ch.qos.logback:logback-classic:1.5.32")
    // 协程
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2")
    // 协程 处理 协程切换（可能线程切换） threadLocal数据丢失问题
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.10.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<Jar>{
    manifest {
        attributes["Main-Class"] = "io.github.AppKt"
    }
    val dependencies: List<Any> = configurations.runtimeClasspath.get().map { it: File ->
        if (it.isDirectory) it else zipTree(it)
    }
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    // exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA") // 必须排除签名文件，否则生成的胖 JAR 无法运行
}

application {
    // Define the main class for the application.
    mainClass = "io.github.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
